version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]
