version: '3.8'

services:
  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run build"
  frontend-publish:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    command: [ "nginx", "-g", "daemon off;" ]
