version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run dev --host"
